/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GenshinBot;

import javax.security.auth.login.LoginException;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;

public class Driver {
	public static void main(String[] args) {
		try {
			JDA jda = JDABuilder.createDefault("Nzk1NzYwNDQzODMzNTgxNjM4.X_ODqg.zwza7jRl1VxSfpZFTkN3sMDD_WY").build();
	        jda.addEventListener(new Calculate());
		} catch (LoginException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

    }

}
